version: "3.8"
services:
  composer:
    image: library/composer:2.0
    environment:
      - COMPOSER_CACHE_DIR=/data/composer_cache_dir
    volumes:
      - .:/app
    restart: never
  test:
    build:
      context: ./docker/test
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - .:/project
      - ./data/test_logs:/logs
    working_dir: /project
    entrypoint: vendor/bin/phpunit
    restart: never
  task_http_dev:
    build:
      context: ./docker/presentation
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - .:/project
      - ./data/presentation_logs:/var/log/apache2
    working_dir: /project
    ports:
      - "80:80"
    restart: always
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      ENV: dev
  task_db_dev:
    env_file:
      - ./.task.env
    image: mariadb:latest
    volumes:
      - ./docker/data/mariadbdata:/var/lib/mysql
      - ./docker/db_dev:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: on-failure
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "8081:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_FILE: /openapi.json
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    links:
      - task_http_dev